### ISSUE TITLE
Problem mit Controller

### ISSUE THREAD

**Issue by akzeitlos** [theorak/datec_booking#1]
Hallo,

ich würde gern die Extension mit Typo3 8.7.9 nutzen. Leider erhalte ich nach Einbindung der Extension folgende Fehlermeldung. Woran kann es liegen?

LG Andreas

#1316104317: The default controller for extension "DatecBooking" and plugin "Booking" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. (More information)

**Comment by theorak** [comment]
Hallo,

zur Nachverfolgung: Beim Update von älteren Versionen (< 1.1.0, pre TYPO3 8 LTS) ist das Inhaltselement neu anzulegen, da T3 8 das Handling leicht verändert hat.

Translation: When updating from an older version of the extension, please re-create the Plugin content element.

**Comment by akzeitlos** [comment]
DANKE

**Comment by akzeitlos** [comment]
Ich stehe echt auf dem Schlauch. Die Validation habe ich doch auch geladen.
Sieht man ja wenn man in den Header schaut. Trotzdem nimmt er es nicht an. Das verstehe ich irgendwie nicht.

LG Andreas

**Comment by theorak** [comment]
Es scheint das JS der Extension aber eher geladen zu werden. Im Header sind compressed JS Dateien vor dem Validation Plugin.
TS-Konfiguration für includeJS mal auf die Reihenfolge prüfen, ich empfehle auch includeJSFooterlibs zu checken und auch das Validation Plugin darüber zu laden, als erstes.

Herzliche Grüße aus Bad Belzig

Philipp Rönsch
Softwareentwickler

Datentechnik Schmidt GmbH
Lübnitzer Str. 28c
14806 Belzig
Telefon: +49 33841 799144
Telefax: +49 33841 799159
www.datec-schmidt.de<http://www.datec-schmidt.de/>

[Beschreibung: Beschreibung: cid:image001.png@01CBDE40.8C9B91F0]

Geschäftsführender Gesellschafter:
Dipl.- Ing. (FH) Ben Schmidt

HRB: 21534, Gerichtsstand: Potsdam
USt-IdNr.: DE 261939446

Von: akzeitlos [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. Januar 2018 11:53
An: theorak/datec_booking <datec_booking@noreply.github.com>
Cc: Philipp Rönsch <p.roensch@datec-schmidt.de>; State change <state_change@noreply.github.com>
Betreff: Re: [theorak/datec_booking] Problem mit Controller (#1)

Ich stehe echt auf dem Schlauch. Die Validation habe ich doch auch geladen.
Sieht man ja wenn man in den Header schaut. Trotzdem nimmt er es nicht an. Das verstehe ich irgendwie nicht.

LG Andreas

**Comment by akzeitlos** [comment]
Danke. Nun geht es.

LG Andreas
